# Promtail Helm Chart Configuration - nprd-apps Overlay
#
# Cluster-specific configuration for nprd-apps cluster
# Uses internal service endpoint since Loki is on the same cluster
#
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: promtail
  namespace: managed-syslog
spec:
  chart: promtail
  repo: https://grafana.github.io/helm-charts
  targetNamespace: managed-syslog
  valuesContent: |-
    # Promtail Configuration - nprd-apps cluster
    # Uses internal service endpoint since Loki is on the same cluster
    
    config:
      global:
        external_labels:
          cluster: "nprd-apps"
      clients:
        # Internal Loki endpoint (same cluster)
        - url: http://loki-distributor.managed-syslog.svc.cluster.local:3100/loki/api/v1/push
      snippets:
        scrapeConfigs: |
          - job_name: kubernetes-pods
            kubernetes_sd_configs:
              - role: pod
            relabel_configs:
              - source_labels:
                  - __meta_kubernetes_pod_controller_name
                regex: ([0-9a-z-.]+?)(-[0-9a-f]+)?$
                action: replace
                target_label: __tmp_controller_name
              - source_labels:
                  - __meta_kubernetes_pod_label_app_kubernetes_io_name
                  - __meta_kubernetes_pod_label_app
                  - __meta_kubernetes_pod_label_name
                  - __tmp_controller_name
                regex: ^;*([^;]+)(;.*)?$
                action: replace
                target_label: app
              - source_labels:
                  - __meta_kubernetes_pod_label_app_kubernetes_io_instance
                  - __meta_kubernetes_pod_label_release
                regex: ^;*([^;]+)(;.*)?$
                action: replace
                target_label: instance
              - source_labels:
                  - __meta_kubernetes_pod_label_app_kubernetes_io_component
                  - __meta_kubernetes_pod_label_component
                regex: ^;*([^;]+)(;.*)?$
                action: replace
                target_label: component
              - action: replace
                source_labels:
                  - __meta_kubernetes_namespace
                target_label: namespace
              - action: replace
                source_labels:
                  - __meta_kubernetes_pod_name
                target_label: pod
              - action: replace
                source_labels:
                  - __meta_kubernetes_pod_container_name
                target_label: container
              - action: replace
                replacement: $1
                separator: /
                source_labels:
                  - namespace
                  - app
                target_label: job
              - action: replace
                source_labels:
                  - __meta_kubernetes_pod_uid
                  - __meta_kubernetes_pod_container_name
                regex: (.+);(.+)
                replacement: /var/log/pods/$1/$2/*.log
                target_label: __path__
    
    # Resources for nprd-apps cluster
    resources:
      requests:
        cpu: 200m
        memory: 256Mi
      limits:
        cpu: 1000m
        memory: 1Gi
    
    # Readiness probe
    readinessProbe:
      httpGet:
        path: /ready
        port: http-metrics
      initialDelaySeconds: 10
      periodSeconds: 10
      failureThreshold: 10
    
    # Image configuration
    image:
      registry: harbor.dataknife.net
      repository: dockerhub/grafana/promtail
      tag: "3.6.2"