# OpenSearch Cluster for Graylog
#
# Deploys OpenSearch using the OpenSearch Kubernetes Operator
# Graylog compatibility: Maximum OpenSearch version is 2.19.3
# WARNING: OpenSearch 3.0+ is NOT supported and will break Graylog!
# See: https://go2docs.graylog.org/current/downloading_and_installing_graylog/compatibility_matrix.htm
#
apiVersion: opensearch.opster.io/v1
kind: OpenSearchCluster
metadata:
  name: graylog-opensearch
  namespace: managed-tools
  labels:
    app: graylog
    component: opensearch
    managed-by: gitops
spec:
  general:
    version: "2.19.3"  # Maximum supported by Graylog (per compatibility matrix - OpenSearch 3.0+ breaks Graylog)
    serviceName: graylog-opensearch  # Service name for OpenSearch cluster
  security:
    config:
      adminCredentialsSecret:
        name: graylog-opensearch-admin-password  # Secret created by operator with password 'admin'
  nodePools:
    - component: masters
      replicas: 1
      roles:
        - master
        - data
      diskSize: "50Gi"
      env:
        - name: OPENSEARCH_INITIAL_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: graylog-opensearch-admin-password
              key: password
      resources:
        requests:
          cpu: "500m"
          memory: "2Gi"
        limits:
          cpu: "2000m"
          memory: "4Gi"
      persistence:
        pvc:
          storageClass: ""  # Use default storage class (truenas-nfs)
          accessModes:
            - ReadWriteOnce  # Required for StatefulSets
    - component: data
      replicas: 1
      roles:
        - data
      diskSize: "250Gi"  # Sized for 2 weeks retention from 2 UniFi instances + growth
      env:
        - name: OPENSEARCH_INITIAL_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: graylog-opensearch-admin-password
              key: password
      resources:
        requests:
          cpu: "500m"
          memory: "2Gi"
        limits:
          cpu: "2000m"
          memory: "4Gi"
      persistence:
        pvc:
          storageClass: ""  # Use default storage class (truenas-nfs)
          accessModes:
            - ReadWriteOnce  # Required for StatefulSets
  dashboards:
    enable: false  # Disable OpenSearch Dashboards (Graylog provides UI)
    replicas: 0  # Required field (0 since disabled)
    version: "2.19.3"  # Required field (same as OpenSearch version)