# Strategic merge patch to inject Kubernetes secrets into Graylog StatefulSet
# This patch replaces hardcoded passwords with secret references
# 
# For MongoDB URI, we use an init container to construct the connection string
# from the secret and write it to a shared volume, then the main container reads it
#
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: graylog
  namespace: managed-graylog
spec:
  template:
    spec:
      # Init container to construct MongoDB URI from secret
      initContainers:
      - name: mongodb-uri-builder
        image: busybox:latest
        command:
        - /bin/sh
        - -c
        - |
          set -e
          echo "Reading MongoDB password from secret..."
          # Read MongoDB password from secret file
          MONGO_PASS=$(cat /etc/secrets/mongodb-password)
          # URL encode the password (basic encoding for special chars in passwords)
          MONGO_PASS_ENC=$(echo -n "$MONGO_PASS" | sed 's/@/%40/g; s/:/%3A/g; s/\//%2F/g; s/\?/%3F/g; s/#/%23/g; s/\[/%5B/g; s/\]/%5D/g; s/ /%20/g')
          # Construct MongoDB URI
          URI="mongodb://graylog:${MONGO_PASS_ENC}@graylog-mongo-rs-svc:27017/graylog?replicaSet=graylog-mongo-rs"
          echo "$URI" > /shared/mongodb-uri
          echo "MongoDB URI constructed and written to /shared/mongodb-uri"
        volumeMounts:
        - name: mongodb-secret
          mountPath: /etc/secrets
          readOnly: true
        - name: shared-data
          mountPath: /shared
      containers:
      - name: graylog
        # Override command to read MongoDB URI from init container before starting Graylog
        command:
        - /bin/sh
        - -c
        - |
          # Read MongoDB URI from init container's shared volume
          if [ -f /shared/mongodb-uri ]; then
            export GRAYLOG_MONGODB_URI=$(cat /shared/mongodb-uri)
            echo "MongoDB URI loaded from init container: ${GRAYLOG_MONGODB_URI%%@*}"
          else
            echo "ERROR: MongoDB URI file not found in /shared/mongodb-uri" >&2
            exit 1
          fi
          # Execute original Graylog entrypoint
          exec /docker-entrypoint.sh
        # Replace env vars with secret references
        env:
        # MongoDB URI will be set from shared volume via command above
        # Password secret from Kubernetes secret
        - name: GRAYLOG_PASSWORD_SECRET
          valueFrom:
            secretKeyRef:
              name: graylog-backup-secret
              key: graylog-secret
        # Root password SHA2 from Kubernetes secret
        - name: GRAYLOG_ROOT_PASSWORD_SHA2
          valueFrom:
            secretKeyRef:
              name: graylog-backup-secret
              key: mongodb-root-password
        volumeMounts:
        - name: mongodb-secret
          mountPath: /etc/secrets
          readOnly: true
        - name: shared-data
          mountPath: /shared
          readOnly: true
      volumes:
      - name: mongodb-secret
        secret:
          secretName: graylog-backup-secret
          items:
          - key: mongodb-db-password
            path: mongodb-password
      - name: shared-data
        emptyDir: {}
