# Patch to fix syslog service selector
# Kustomize commonLabels adds app=graylog to selector, but pod has app=graylog-app
# This strategic merge patch completely replaces the selector
apiVersion: v1
kind: Service
metadata:
  name: graylog-syslog
  namespace: managed-graylog
spec:
  # Use $patch: replace to completely replace selector (overrides commonLabels)
  $patch: replace
  selector:
    app: graylog-app
    app.kubernetes.io/name: graylog
