# Graylog Helm Chart Configuration - nprd-apps Overlay
#
# Cluster-specific configuration for nprd-apps cluster
# This overrides base configuration with cluster-specific settings
#
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: graylog
  namespace: managed-graylog
spec:
  chart: graylog
  repo: https://graylog2.github.io/graylog-helm
  targetNamespace: managed-graylog
  valuesContent: |-
    # Graylog Configuration - nprd-apps cluster
    graylog:
      image:
        repository: graylog/graylog
        tag: "5.2"
      replicas: 1
      resources:
        requests:
          cpu: 500m
          memory: 1Gi
        limits:
          cpu: 2000m
          memory: 4Gi
      # Graylog web interface port
      service:
        type: ClusterIP
        port: 9000
        targetPort: 9000
      # Java heap size (should be 50% of memory limit)
      javaOpts: "-Xms2g -Xmx2g -XX:NewRatio=1 -server -XX:+ResizeTLAB -XX:+UseConcMarkSweepGC -XX:+CMSConcurrentMTEnabled -XX:+CMSClassUnloadingEnabled -XX:+UseParNewGC -XX:-OmitStackTraceInFastThrow"
      # Environment variables for Graylog configuration
      env:
        # Graylog root timezone
        TZ: UTC
        # Graylog server bind address
        GRAYLOG_HTTP_BIND_ADDRESS: 0.0.0.0:9000
        # Graylog external URI (for web UI links)
        GRAYLOG_HTTP_EXTERNAL_URI: https://graylog.dataknife.net/
        # Elasticsearch/OpenSearch connection
        # Using external OpenSearch cluster (datanodes disabled)
        # Service name: graylog-opensearch (managed by OpenSearch Kubernetes Operator)
        GRAYLOG_ELASTICSEARCH_HOSTS: http://graylog-opensearch:9200
        # MongoDB connection (with authentication)
        # SECURITY: Password is injected via secret reference using Job patch (graylog-secret-patch-job.yaml)
        # The patch job replaces these placeholders with proper secret-based configuration
        GRAYLOG_MONGODB_URI: "PLACEHOLDER_WILL_BE_REPLACED_BY_PATCH"
        # Password secret (injected via secret reference in patch)
        GRAYLOG_PASSWORD_SECRET: "PLACEHOLDER_WILL_BE_REPLACED_BY_PATCH"
        # Root password SHA2 (injected via secret reference in patch)
        GRAYLOG_ROOT_PASSWORD_SHA2: "PLACEHOLDER_WILL_BE_REPLACED_BY_PATCH"
        # Index rotation and retention configuration (configured via Graylog web UI after deployment)
        # Recommended settings for 2 weeks retention:
        #   - Index rotation strategy: Daily (rotate index every day)
        #   - Index retention: 14 days (keep indices for 2 weeks)
        #   - Max number of indices: 20 (14 days + buffer)
        #   - Index deletion: Delete closed indices older than 14 days
        # Note: These settings are configured in Graylog web UI under System → Indices
    
    # MongoDB Configuration (Graylog metadata store)
    # Using MongoDB Community Operator (communityResource)
    mongodb:
      communityResource:
        enabled: true
      version: "7.0.25"
      replicas: 1  # Single replica for standalone deployment
      arbiters: 0  # No arbiters for standalone
      persistence:
        storageClass: ""
        size:
          data: "20Gi"
          logs: "2Gi"
    
    # Datanode Configuration (disabled - using external OpenSearch)
    datanode:
      enabled: false
    
    # Ingress Configuration for nprd-apps cluster
    ingress:
      enabled: true
      className: nginx
      annotations:
        nginx.ingress.kubernetes.io/ssl-redirect: "true"
        nginx.ingress.kubernetes.io/proxy-body-size: "0"
        nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
        nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
        # Note: TLS secret 'wildcard-dataknife-net-tls' must exist in the namespace
        # Use the generate-wildcard-cert.sh script to create a cluster-wide wildcard certificate
      hosts:
        - host: graylog.dataknife.net
          paths:
            - path: /
              pathType: Prefix
      tls:
        enabled: true
        secretName: wildcard-dataknife-net-tls
    
    # Persistence for Graylog (optional, typically not needed as logs stored in OpenSearch)
    persistence:
      enabled: false
    
    # Security Context
    securityContext:
      runAsUser: 1100
      runAsGroup: 1100
      fsGroup: 1100
