# Job to initialize OpenSearch security by running securityadmin.sh
# This creates the .opendistro_security index required for OpenSearch security
# Based on: https://forum.opensearch.org/t/opensearch-deployment-with-opensearch-operator-failure-no-such-index-opendistro-security-solved/20001
#
# NOTE: Jobs have immutable spec.template fields. When this Job spec changes,
# Fleet will show an error but the Job will still be created with a new name.
# The error can be ignored as the Job is idempotent and will work correctly.
#
apiVersion: batch/v1
kind: Job
metadata:
  name: opensearch-security-init
  namespace: managed-graylog
  annotations:
    # Fleet cannot patch Jobs because spec.template is immutable
    # Fleet will show ErrApplied status, but the Job will be created and work correctly
    # To update the Job, delete it manually and Fleet will recreate it
    fleet.cattle.io/keep-resources: "false"
  labels:
    app: graylog
    component: opensearch-security-init
    managed-by: gitops
spec:
  # Run only once
  backoffLimit: 3
  ttlSecondsAfterFinished: 3600  # Keep for 1 hour
  template:
    metadata:
      labels:
        app: graylog
        component: opensearch-security-init
        managed-by: gitops
    spec:
      serviceAccountName: opensearch-security-init
      restartPolicy: Never
      containers:
      - name: security-init
        image: opensearchproject/opensearch:2.19.3  # Match OpenSearch version
        command:
        - /bin/bash
        - -c
        - |
          set -e
          
          NAMESPACE="managed-graylog"
          CLUSTER_NAME="graylog-opensearch"
          SERVICE_HOSTNAME="${CLUSTER_NAME}.${NAMESPACE}.svc.cluster.local"
          
          echo "=== OpenSearch Security Initialization Job ==="
          echo ""
          echo "Waiting for OpenSearch cluster to be ready..."
          
          # Wait for OpenSearch service to be available (max 5 minutes)
          for i in {1..60}; do
            if curl -k --silent --connect-timeout 5 "https://${SERVICE_HOSTNAME}:9200" >/dev/null 2>&1; then
              echo "✅ OpenSearch service is responding"
              break
            fi
            if [ $i -eq 60 ]; then
              echo "❌ ERROR: OpenSearch service not available after 5 minutes"
              exit 1
            fi
            echo "Waiting for OpenSearch service... ($i/60)"
            sleep 5
          done
          
          # Wait for cluster to be in green/yellow state (max 5 minutes)
          echo "Waiting for OpenSearch cluster to be ready..."
          for i in {1..60}; do
            CLUSTER_HEALTH=$(curl -k --silent --connect-timeout 5 "https://${SERVICE_HOSTNAME}:9200/_cluster/health" 2>/dev/null || echo "")
            if [ -n "$CLUSTER_HEALTH" ]; then
              STATUS=$(echo "$CLUSTER_HEALTH" | grep -o '"status":"[^"]*"' | cut -d'"' -f4 || echo "")
              if [ "$STATUS" = "green" ] || [ "$STATUS" = "yellow" ]; then
                echo "✅ OpenSearch cluster is $STATUS"
                break
              fi
            fi
            if [ $i -eq 60 ]; then
              echo "⚠️  WARNING: OpenSearch cluster not in green/yellow state, continuing anyway..."
            fi
            echo "Waiting for cluster health... ($i/60)"
            sleep 5
          done
          
          echo ""
          echo "Preparing certificates for securityadmin.sh..."
          
          # Admin certificate is already in PKCS8 format (generated by script)
          ADMIN_KEY="/tmp/admin-key.pem"
          ADMIN_CERT="/tmp/admin.pem"
          ROOT_CA="/tmp/root-ca.pem"
          
          # Copy admin certificates from mounted secret (already in PKCS8 format)
          cp /etc/opensearch-admin-certs/admin-key.pem "$ADMIN_KEY"
          cp /etc/opensearch-admin-certs/admin.pem "$ADMIN_CERT"
          cp /etc/opensearch-admin-certs/ca.crt "$ROOT_CA"
          
          # Verify key is in PKCS8 format (securityadmin.sh requirement)
          if ! openssl pkcs8 -in "$ADMIN_KEY" -nocrypt -noout >/dev/null 2>&1; then
            echo "⚠️  WARNING: Admin key is not in PKCS8 format, converting..."
            openssl pkcs8 -topk8 -nocrypt -in "$ADMIN_KEY" -out "${ADMIN_KEY}.pkcs8"
            mv "${ADMIN_KEY}.pkcs8" "$ADMIN_KEY"
          else
            echo "✅ Admin key is in PKCS8 format"
          fi
          
          # Set permissions
          chmod 600 "$ADMIN_KEY"
          chmod 644 "$ADMIN_CERT"
          chmod 644 "$ROOT_CA"
          
          echo "✅ Certificates prepared"
          echo ""
          
          echo "Running securityadmin.sh to initialize security..."
          echo ""
          
          # Path to securityadmin.sh in OpenSearch image
          SECURITYADMIN="/usr/share/opensearch/plugins/opensearch-security/tools/securityadmin.sh"
          
          # Check if securityadmin.sh exists
          if [ ! -f "$SECURITYADMIN" ]; then
            echo "❌ ERROR: securityadmin.sh not found at $SECURITYADMIN"
            exit 1
          fi
          
          # Make it executable
          chmod +x "$SECURITYADMIN"
          
          # Run securityadmin.sh to initialize security
          # -cd: config directory (use default)
          # -icl: initialize configuration in cluster
          # -nhnv: no hostname verification
          # -cacert: CA certificate
          # -cert: admin certificate
          # -key: admin key
          # --accept-red-cluster: accept red cluster state
          # -h: OpenSearch host
          # -p: OpenSearch port
          # -ts: truststore location (if needed)
          # -tspass: truststore password
          
          echo "Executing: $SECURITYADMIN -cd /usr/share/opensearch/plugins/opensearch-security/securityconfig -icl -nhnv -cacert $ROOT_CA -cert $ADMIN_CERT -key $ADMIN_KEY --accept-red-cluster -h $SERVICE_HOSTNAME -p 9200"
          echo ""
          
          # Run securityadmin.sh with retries (it may fail if cluster is still initializing)
          MAX_RETRIES=5
          RETRY_COUNT=0
          SUCCESS=false
          
          while [ $RETRY_COUNT -lt $MAX_RETRIES ]; do
            if $SECURITYADMIN \
              -cd /usr/share/opensearch/plugins/opensearch-security/securityconfig \
              -icl \
              -nhnv \
              -cacert "$ROOT_CA" \
              -cert "$ADMIN_CERT" \
              -key "$ADMIN_KEY" \
              --accept-red-cluster \
              -h "$SERVICE_HOSTNAME" \
              -p 9200; then
              SUCCESS=true
              break
            fi
            
            RETRY_COUNT=$((RETRY_COUNT + 1))
            if [ $RETRY_COUNT -lt $MAX_RETRIES ]; then
              echo "⚠️  securityadmin.sh failed, retrying in 30 seconds... ($RETRY_COUNT/$MAX_RETRIES)"
              sleep 30
            fi
          done
          
          if [ "$SUCCESS" = true ]; then
            echo ""
            echo "✅ Security initialization completed successfully"
            echo ""
            echo "Verifying .opendistro_security index exists..."
            
            # Verify the index was created
            sleep 5
            INDEX_EXISTS=$(curl -k --silent --connect-timeout 5 "https://${SERVICE_HOSTNAME}:9200/.opendistro_security" 2>/dev/null || echo "")
            if [ -n "$INDEX_EXISTS" ]; then
              echo "✅ .opendistro_security index exists"
            else
              echo "⚠️  WARNING: Could not verify .opendistro_security index (this may be normal if auth is required)"
            fi
          else
            echo ""
            echo "❌ ERROR: securityadmin.sh failed after $MAX_RETRIES attempts"
            echo "This may indicate:"
            echo "  - OpenSearch cluster is not fully ready"
            echo "  - Certificate DN mismatch (check adminDn in opensearch-cluster.yaml)"
            echo "  - Network connectivity issues"
            exit 1
          fi
          
          echo ""
          echo "✅ Security initialization job completed"
        volumeMounts:
        - name: opensearch-admin-certs
          mountPath: /etc/opensearch-admin-certs
          readOnly: true
      volumes:
      - name: opensearch-admin-certs
        secret:
          secretName: graylog-opensearch-admin-certs
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: opensearch-security-init
  namespace: managed-graylog
  labels:
    app: graylog
    component: opensearch-security-init
    managed-by: gitops
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: opensearch-security-init
  namespace: managed-graylog
  labels:
    app: graylog
    component: opensearch-security-init
    managed-by: gitops
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get"]
  resourceNames: ["graylog-opensearch-admin-certs"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: opensearch-security-init
  namespace: managed-graylog
  labels:
    app: graylog
    component: opensearch-security-init
    managed-by: gitops
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: opensearch-security-init
subjects:
- kind: ServiceAccount
  name: opensearch-security-init
  namespace: managed-graylog
