# OpenSearch Cluster for Graylog - nprd-apps Overlay
#
# Deploys OpenSearch using the OpenSearch Kubernetes Operator
# Graylog 5.2 supports OpenSearch 2.x (tested up to 2.15)
#
apiVersion: opensearch.opster.io/v1
kind: OpenSearchCluster
metadata:
  name: graylog-opensearch
  namespace: managed-tools
  labels:
    app: graylog
    component: opensearch
    managed-by: gitops
    cluster: nprd-apps
spec:
  general:
    version: "2.15.0"  # Latest OpenSearch version compatible with Graylog 5.2
    serviceName: graylog-opensearch  # Service name for OpenSearch cluster
    additionalConfig:
      plugins.security.disabled: "true"  # Disable security plugin (Graylog handles authentication)
  nodePools:
    - component: masters
      replicas: 1
      roles:
        - master
        - data
      diskSize: "50Gi"
      resources:
        requests:
          cpu: "500m"
          memory: "2Gi"
        limits:
          cpu: "2000m"
          memory: "4Gi"
      persistence:
        pvc:
          storageClass: ""  # Use default storage class (truenas-nfs)
    - component: data
      replicas: 1
      roles:
        - data
      diskSize: "250Gi"  # Sized for 2 weeks retention from 2 UniFi instances + growth
      resources:
        requests:
          cpu: "500m"
          memory: "2Gi"
        limits:
          cpu: "2000m"
          memory: "4Gi"
      persistence:
        pvc:
          storageClass: ""  # Use default storage class (truenas-nfs)
  dashboards:
    enable: false  # Disable OpenSearch Dashboards (Graylog provides UI)
    replicas: 0  # Required field (0 since disabled)
    version: "2.15.0"  # Required field (same as OpenSearch version)