# OpenSearch Cluster for Graylog - nprd-apps Overlay
#
# Deploys OpenSearch using the OpenSearch Kubernetes Operator
# Graylog compatibility: Maximum OpenSearch version is 2.19.3
# WARNING: OpenSearch 3.0+ is NOT supported and will break Graylog!
# See: https://go2docs.graylog.org/current/downloading_and_installing_graylog/compatibility_matrix.htm
#
apiVersion: opensearch.opster.io/v1
kind: OpenSearchCluster
metadata:
  name: graylog-opensearch
  namespace: managed-graylog
  labels:
    app: graylog
    component: opensearch
    managed-by: gitops
    cluster: nprd-apps
spec:
  general:
    version: "2.19.3"  # Maximum supported by Graylog (per compatibility matrix - OpenSearch 3.0+ breaks Graylog)
    serviceName: graylog-opensearch  # Service name for OpenSearch cluster
    # Configure initial cluster manager nodes for cluster formation
    # This tells OpenSearch which nodes should be the initial cluster managers
    additionalConfig:
      cluster.initial_cluster_manager_nodes: "graylog-opensearch-masters-0"
      # Configure network publish host to use service hostname
      # This helps with certificate hostname matching when clients connect via service
      network.publish_host: "graylog-opensearch.managed-graylog.svc.cluster.local"
  security:
    config:
      adminCredentialsSecret:
        name: graylog-opensearch-admin-password  # Secret for operator access (post-bootstrap)
    # Use custom TLS certificates with correct hostname (graylog-opensearch)
    # Certificates generated with: scripts/generate-opensearch-certs.sh
    # Certificates include service hostname and pod hostnames in SAN
    tls:
      http:
        generate: false  # Use custom certificates instead of auto-generated
        secret:
          name: graylog-opensearch-http-certs  # Secret with tls.crt, tls.key, ca.crt
        caSecret:
          name: graylog-opensearch-ca  # CA certificate for trust
      transport:
        generate: false  # Use custom certificates instead of auto-generated
        secret:
          name: graylog-opensearch-transport-certs  # Secret with tls.crt, tls.key, ca.crt
        caSecret:
          name: graylog-opensearch-ca  # CA certificate for trust
        # Certificate DN from our custom certificate
        # Full DN: CN=graylog-opensearch, OU=OpenSearch, O=Graylog, L=Internal, ST=Internal, C=US
        # Allow nodes with this certificate to connect
        nodesDn:
          - "CN=graylog-opensearch, OU=OpenSearch, O=Graylog"  # Match exact CN, OU, O
          - "CN=graylog-opensearch-masters-0, OU=OpenSearch, O=Graylog"  # Match master node
          - "CN=graylog-opensearch-data-0, OU=OpenSearch, O=Graylog"  # Match data node
          - "CN=graylog-opensearch*, OU=OpenSearch, O=Graylog"  # Wildcard for any node with this prefix
        # Admin certificate DN (for operator access)
        adminDn:
          - "CN=graylog-opensearch, OU=OpenSearch, O=Graylog"
  nodePools:
    - component: masters
      replicas: 1
      roles:
        - master
        - data
      diskSize: "50Gi"
      env:
        - name: OPENSEARCH_INITIAL_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: graylog-opensearch-admin-password
              key: password
      resources:
        requests:
          cpu: "500m"
          memory: "2Gi"
        limits:
          cpu: "2"  # Operator normalizes "2000m" to "2" - using operator format to prevent drift
          memory: "4Gi"
      persistence:
        pvc:
          storageClass: ""  # Use default storage class (truenas-nfs)
          accessModes:
            - ReadWriteOnce  # Required for StatefulSets
    - component: data
      replicas: 1
      roles:
        - data
      diskSize: "250Gi"  # Sized for 2 weeks retention from 2 UniFi instances + growth
      env:
        - name: OPENSEARCH_INITIAL_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: graylog-opensearch-admin-password
              key: password
      resources:
        requests:
          cpu: "500m"
          memory: "2Gi"
        limits:
          cpu: "2"  # Operator normalizes "2000m" to "2" - using operator format to prevent drift
          memory: "4Gi"
      persistence:
        pvc:
          storageClass: ""  # Use default storage class (truenas-nfs)
          accessModes:
            - ReadWriteOnce  # Required for StatefulSets
  dashboards:
    enable: false  # Disable OpenSearch Dashboards (Graylog provides UI)
    replicas: 0  # Required field (0 since disabled)
    version: "2.19.3"  # Required field (same as OpenSearch version)