# Loki Helm Chart Configuration
#
# Deploys Loki (log aggregation) using the official Grafana Loki Helm chart
# Official repository: https://grafana.github.io/helm-charts
# Chart: https://github.com/grafana/helm-charts/tree/main/charts/loki
# Documentation: https://grafana.com/docs/loki/latest/setup/install/helm/
#
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: loki
  namespace: managed-syslog
spec:
  chart: loki
  repo: https://grafana.github.io/helm-charts
  targetNamespace: managed-syslog
  valuesContent: |-
    # Loki Configuration - Latest stable version 3.6.2
    # Microservices mode (Distributed) - recommended for production workloads requiring high availability
    # Documentation: https://grafana.com/docs/loki/latest/get-started/deployment-modes/#microservices-mode
    deploymentMode: Distributed
    
    # Authentication
    auth_enabled: false
    
    # Common configuration
    commonConfig:
      replication_factor: 1
    
    # Loki configuration block (required for microservices mode)
    loki:
      # Storage configuration
      storage:
        type: s3
        bucketNames:
          chunks: loki-chunks
          ruler: loki-ruler
        s3:
          endpoint: http://loki-minio:9000
          region: us-east-1
          bucketNames:
            chunks: loki-chunks
            ruler: loki-ruler
          accessKeyId: minioadmin
          secretAccessKey: minioadmin
          s3ForcePathStyle: true
      
      # Schema configuration (required)
      schemaConfig:
        configs:
          - from: "2020-10-24"
            store: tsdb
            object_store: s3
            schema: v13
            index:
              prefix: index_
              period: 24h
    
    # Storage configuration (top-level for chart compatibility)
    # Using MinIO as S3-compatible object storage for microservices mode
    storage:
      type: s3
      bucketNames:
        chunks: loki-chunks
        ruler: loki-ruler
      s3:
        endpoint: http://loki-minio:9000
        region: us-east-1
        bucketNames:
          chunks: loki-chunks
          ruler: loki-ruler
        accessKeyId: minioadmin
        secretAccessKey: minioadmin
        s3ForcePathStyle: true
    
    # MinIO configuration (local S3-compatible storage)
    minio:
      enabled: true
      defaultBuckets: "loki-chunks,loki-ruler"
      persistence:
        enabled: true
        storageClass: ""
        size: 50Gi  # Base size, overlay will customize
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 500m
          memory: 512Mi
    
    # Limits configuration
    limits:
      retention_period: 168h  # 7 days base retention
      ingestion_rate_mb: 16
      ingestion_burst_size_mb: 32
      per_stream_rate_limit: 4MB
      per_stream_rate_limit_burst: 8MB
    
    # Compactor configuration
    compactor:
      retentionEnabled: true
      retentionDeleteDelay: 2h
      retentionDeleteWorkerCount: 150
      persistence:
        enabled: true
        storageClass: ""
        size: 50Gi
    
    # Gateway configuration (for ingress and routing)
    # Disabled - using custom ingress and direct service access
    gateway:
      enabled: false
      replicas: 0
    
    # Chunks cache (memcached) - Disabled due to insufficient memory
    chunksCache:
      enabled: false
    
    # Disable other deployment modes to avoid conflicts
    singleBinary:
      enabled: false
      replicas: 0
    simpleScalable:
      enabled: false
      replicas: 0
    backend:
      enabled: false
      replicas: 0
    read:
      enabled: false
      replicas: 0
    write:
      enabled: false
      replicas: 0
    
    # Microservices Components
    
    # Distributor - Handles incoming log data
    distributor:
      replicas: 1
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 500m
          memory: 512Mi
    
    # Ingester - Processes and stores log data temporarily
    ingester:
      replicas: 1
      persistence:
        enabled: true
        storageClass: ""
        size: 50Gi  # Base size, overlay will customize
      resources:
        requests:
          cpu: 200m
          memory: 512Mi
        limits:
          cpu: 1000m
          memory: 2Gi
    
    # Querier - Executes queries against stored log data
    querier:
      replicas: 1
      resources:
        requests:
          cpu: 200m
          memory: 512Mi
        limits:
          cpu: 1000m
          memory: 2Gi
    
    # Query Frontend - Manages and optimizes query execution
    queryFrontend:
      replicas: 1
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 500m
          memory: 512Mi
    
    # Index Gateway - Manages indexing operations
    indexGateway:
      replicas: 1
      persistence:
        enabled: true
        storageClass: ""
        size: 10Gi
      resources:
        requests:
          cpu: 100m
          memory: 256Mi
        limits:
          cpu: 500m
          memory: 1Gi
    
    # Query Scheduler - Schedules query execution tasks
    queryScheduler:
      replicas: 1
      resources:
        requests:
          cpu: 50m
          memory: 64Mi
        limits:
          cpu: 200m
          memory: 256Mi
    
    # Ruler - Evaluates alerting and recording rules
    ruler:
      replicas: 1
      persistence:
        enabled: true
        storageClass: ""
        size: 10Gi
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 500m
          memory: 512Mi
    
    # Service configuration
    service:
      type: ClusterIP
      port: 3100
    
    # Image configuration
    image:
      registry: harbor.dataknife.net
      repository: dockerhub/library/grafana/loki
      tag: "3.6.2"  # Latest stable version
