# Promtail Helm Chart Configuration
#
# Deploys Promtail (log collection agent) using the official Grafana Promtail Helm chart
# Official repository: https://grafana.github.io/helm-charts
# Chart: https://github.com/grafana/helm-charts/tree/main/charts/promtail
#
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: promtail
  namespace: managed-syslog
spec:
  chart: promtail
  repo: https://grafana.github.io/helm-charts
  targetNamespace: managed-syslog
  valuesContent: |-
    # Promtail Configuration - Latest stable version 3.6.2 (matches Loki)
    config:
      clients:
        # Using distributor directly for microservices mode
        - url: http://loki-distributor:3100/loki/api/v1/push
      snippets:
        scrapeConfigs: |
          - job_name: kubernetes-pods
            kubernetes_sd_configs:
              - role: pod
            relabel_configs:
              - source_labels:
                  - __meta_kubernetes_pod_controller_name
                regex: ([0-9a-z-.]+?)(-[0-9a-f]+)?$
                action: replace
                target_label: __tmp_controller_name
              - source_labels:
                  - __meta_kubernetes_pod_label_app_kubernetes_io_name
                  - __meta_kubernetes_pod_label_app
                  - __meta_kubernetes_pod_label_name
                  - __tmp_controller_name
                regex: ^;*([^;]+)(;.*)?$
                action: replace
                target_label: app
              - source_labels:
                  - __meta_kubernetes_pod_label_app_kubernetes_io_instance
                  - __meta_kubernetes_pod_label_release
                regex: ^;*([^;]+)(;.*)?$
                action: replace
                target_label: instance
              - source_labels:
                  - __meta_kubernetes_pod_label_app_kubernetes_io_component
                  - __meta_kubernetes_pod_label_component
                regex: ^;*([^;]+)(;.*)?$
                action: replace
                target_label: component
              - action: replace
                source_labels:
                  - __meta_kubernetes_namespace
                target_label: namespace
              - action: replace
                source_labels:
                  - __meta_kubernetes_pod_name
                target_label: pod
              - action: replace
                source_labels:
                  - __meta_kubernetes_pod_container_name
                target_label: container
              - action: replace
                replacement: $1
                separator: /
                source_labels:
                  - namespace
                  - app
                target_label: job
              - action: replace
                source_labels:
                  - __meta_kubernetes_pod_uid
                  - __meta_kubernetes_pod_container_name
                regex: (.+);(.+)
                replacement: /var/log/pods/$1/*.log
                target_label: __path__
              - action: replace
                regex: true
                source_labels:
                  - __meta_kubernetes_pod_controller_name
                target_label: __tmp_controller_type
              - action: replace
                regex: ^([^;]+);([^;]+);([^;]+)$
                source_labels:
                  - __tmp_controller_type
                  - __meta_kubernetes_pod_label_app_kubernetes_io_component
                  - __meta_kubernetes_pod_label_component
                target_label: __tmp_controller_component
              - action: keep
                regex: ^(StatefulSet|DaemonSet|Deployment|CronJob|Job)
                source_labels:
                  - __tmp_controller_type
              - action: replace
                source_labels:
                  - __meta_kubernetes_pod_label_app_kubernetes_io_name
                  - __meta_kubernetes_pod_label_app
                  - __meta_kubernetes_pod_label_name
                  - __tmp_controller_name
                regex: ^;*([^;]+)(;.*)?$
                target_label: app
              - action: replace
                source_labels:
                  - __meta_kubernetes_pod_label_app_kubernetes_io_instance
                  - __meta_kubernetes_pod_label_release
                regex: ^;*([^;]+)(;.*)?$
                target_label: instance
              - action: replace
                source_labels:
                  - __meta_kubernetes_pod_label_app_kubernetes_io_component
                  - __meta_kubernetes_pod_label_component
                regex: ^;*([^;]+)(;.*)?$
                target_label: component
              - action: replace
                source_labels:
                  - __meta_kubernetes_namespace
                target_label: namespace
              - action: replace
                source_labels:
                  - __meta_kubernetes_pod_name
                target_label: pod
              - action: replace
                source_labels:
                  - __meta_kubernetes_pod_container_name
                target_label: container
              - action: replace
                replacement: $1
                separator: /
                source_labels:
                  - namespace
                  - app
                target_label: job
              - action: replace
                source_labels:
                  - __meta_kubernetes_pod_uid
                  - __meta_kubernetes_pod_container_name
                regex: (.+);(.+)
                replacement: /var/log/pods/$1/$2/*.log
                target_label: __path__
    # Resources
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 512Mi
    # Image configuration
    image:
      registry: docker.io
      repository: grafana/promtail
      tag: "3.6.2"  # Latest stable version (matches Loki)
