apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: harbor
  namespace: managed-tools
spec:
  chart: harbor
  repo: https://helm.goharbor.io
  targetNamespace: managed-tools
  valuesContent: |-
    expose:
      type: ingress
      tls:
        enabled: true
        certSource: secret
        secret:
          secretName: wildcard-dataknife-net-tls
          notarySecretName: wildcard-dataknife-net-tls
      ingress:
        hosts:
          core: harbor.dataknife.net
          notary: notary.dataknife.net
        className: nginx
        annotations:
          nginx.ingress.kubernetes.io/ssl-redirect: "true"
          nginx.ingress.kubernetes.io/proxy-body-size: "0"
          # Note: TLS secret 'wildcard-dataknife-net-tls' must be created manually for internal DNS
          # Use the generate-wildcard-cert.sh script to create a cluster-wide wildcard certificate
    externalURL: https://harbor.dataknife.net
    # Harbor admin password - MUST be set via harbor-credentials secret
    # Create secret using: ./scripts/create-harbor-secrets.sh
    # Or manually: kubectl create secret generic harbor-credentials -n managed-tools --from-literal=harborAdminPassword=<password>
    # Using existingSecret to reference the harbor-credentials secret
    # The secret must contain the key 'harborAdminPassword'
    existingSecret: harbor-credentials
    # Secret key name for admin password (must match the key in the secret)
    secretKey: harborAdminPassword
    # Database configuration
    database:
      type: postgresql
      internal:
        # Database password - MUST be set via harbor-credentials secret
        # Using existingSecret to reference the harbor-credentials secret
        # The secret must contain the key 'databasePassword'
        existingSecret: harbor-credentials
        # Secret key name for database password (must match the key in the secret)
        secretKey: databasePassword
        database: "registry"
        maxIdleConns: 50
        maxOpenConns: 100
    redis:
      type: internal
      internal:
        # Redis password - optional, set via harbor-credentials secret if needed
        # Using existingSecret to reference the harbor-credentials secret
        # The secret must contain the key 'redisPassword' (can be empty string)
        existingSecret: harbor-credentials
        # Secret key name for redis password (must match the key in the secret)
        secretKey: redisPassword
    persistence:
      enabled: true
      resourcePolicy: "keep"
      persistentVolumeClaim:
        registry:
          storageClass: ""
          accessMode: ReadWriteOnce
          size: 5Gi
        chartmuseum:
          storageClass: ""
          accessMode: ReadWriteOnce
          size: 5Gi
        jobservice:
          storageClass: ""
          accessMode: ReadWriteOnce
          size: 1Gi
        database:
          storageClass: ""
          accessMode: ReadWriteOnce
          size: 1Gi
        redis:
          storageClass: ""
          accessMode: ReadWriteOnce
          size: 1Gi
        trivy:
          storageClass: ""
          accessMode: ReadWriteOnce
          size: 5Gi
    core:
      replicas: 1
      resources:
        requests:
          cpu: 100m
          memory: 256Mi
        limits:
          cpu: 500m
          memory: 512Mi
    jobservice:
      replicas: 1
      resources:
        requests:
          cpu: 100m
          memory: 256Mi
        limits:
          cpu: 500m
          memory: 512Mi
    registry:
      replicas: 1
      resources:
        requests:
          cpu: 100m
          memory: 256Mi
        limits:
          cpu: 1000m
          memory: 1Gi
    chartmuseum:
      enabled: true
      replicas: 1
      resources:
        requests:
          cpu: 50m
          memory: 128Mi
        limits:
          cpu: 200m
          memory: 256Mi
    trivy:
      enabled: true
      replicas: 1
      resources:
        requests:
          cpu: 100m
          memory: 256Mi
        limits:
          cpu: 500m
          memory: 512Mi
    notary:
      enabled: true
    logLevel: info
    metrics:
      enabled: false
