apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: harbor-postgresql
  namespace: managed-tools
  labels:
    app: harbor
    component: database
    managed-by: gitops
spec:
  instances: 2
  # PostgreSQL version - using 16.2 (latest stable)
  imageName: ghcr.io/cloudnative-pg/postgresql:16.2
  
  # Bootstrap configuration
  bootstrap:
    initdb:
      database: registry
      owner: harbor
      secret:
        name: harbor-postgresql-credentials
      dataChecksums: true
      encoding: UTF8
      localeCType: C
      localeCollate: C
  
  # PostgreSQL configuration
  postgresql:
    parameters:
      max_connections: "200"
      shared_buffers: "256MB"
      effective_cache_size: "1GB"
      maintenance_work_mem: "64MB"
      checkpoint_completion_target: "0.9"
      wal_buffers: "16MB"
      default_statistics_target: "100"
      random_page_cost: "1.1"
      effective_io_concurrency: "200"
      work_mem: "4MB"
      min_wal_size: "1GB"
      max_wal_size: "4GB"
  
  # Storage configuration
  storage:
    size: 20Gi
    storageClass: "truenas-nfs"  # Use truenas-nfs storage class
  
  # Resource requests and limits
  resources:
    requests:
      memory: "256Mi"
      cpu: "250m"
    limits:
      memory: "1Gi"
      cpu: "1000m"
  
  # High Availability settings
  postgres:
    syncReplicaElectionConstraint: true
  maxSyncReplicas: 1
  minSyncReplicas: 1
  
  # Enable connection pooling with PgBouncer
  enablePooler: true
  pooler:
    instances: 2
    type: rw
    pgbouncer:
      parameters:
        max_client_conn: "1000"
        default_pool_size: "25"
  
  # Monitoring
  monitoring:
    enabled: true
    disableDefaultQueries: false
