apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: containerd-harbor-cert-config
  namespace: managed-cicd
  labels:
    app: containerd-harbor-cert-config
    managed-by: gitops
spec:
  selector:
    matchLabels:
      app: containerd-harbor-cert-config
  template:
    metadata:
      labels:
        app: containerd-harbor-cert-config
        managed-by: gitops
    spec:
      # Run on all nodes (including control-plane)
      tolerations:
        # Allow running on control-plane nodes (RKE2 doesn't have taints by default, but this is good practice)
        - effect: NoSchedule
          operator: Exists
        - effect: NoExecute
          operator: Exists
      # Use host network to access node filesystem
      hostNetwork: true
      # Privileged container to write to node filesystem
      containers:
      - name: cert-config
        image: harbor.dataknife.net/dockerhub/library/alpine:latest
        command:
        - /bin/sh
        - -c
        - |
          set -e
          
          HARBOR_URL="harbor.dataknife.net"
          MOUNTED_CERT="/cert/ca.crt"
          
          # RKE2 registry configuration paths
          RKE2_REGISTRY_DIR="/etc/rancher/rke2"
          RKE2_REGISTRY_YAML="${RKE2_REGISTRY_DIR}/registries.yaml"
          RKE2_CERT_FILE="${RKE2_REGISTRY_DIR}/harbor-ca.crt"
          
          # Also configure containerd certs.d directory (backup method)
          CONTAINERD_CERTS_DIR="/var/lib/rancher/rke2/agent/etc/containerd/certs.d/${HARBOR_URL}"
          CONTAINERD_CERT_FILE="${CONTAINERD_CERTS_DIR}/ca.crt"
          
          echo "Configuring RKE2 to trust Harbor registry certificate..."
          echo "RKE2 registry config: ${RKE2_REGISTRY_YAML}"
          echo "RKE2 certificate file: ${RKE2_CERT_FILE}"
          echo "Mounted certificate: ${MOUNTED_CERT}"
          
          # Check if mounted certificate exists
          if [ ! -f "${MOUNTED_CERT}" ]; then
            echo "Error: Mounted certificate not found at ${MOUNTED_CERT}"
            exit 1
          fi
          
          # Create RKE2 registry directory
          echo "Creating RKE2 registry directory: ${RKE2_REGISTRY_DIR}"
          mkdir -p "${RKE2_REGISTRY_DIR}"
          
          # Copy certificate for RKE2 registries.yaml
          echo "Copying certificate to ${RKE2_CERT_FILE}"
          cp "${MOUNTED_CERT}" "${RKE2_CERT_FILE}"
          chmod 644 "${RKE2_CERT_FILE}"
          
          # Create RKE2 registries.yaml configuration
          echo "Creating RKE2 registries.yaml configuration..."
          cat > "${RKE2_REGISTRY_YAML}" <<EOF
          mirrors:
            "${HARBOR_URL}":
              endpoint:
                - "https://${HARBOR_URL}"
          configs:
            "${HARBOR_URL}":
              tls:
                ca_file: "${RKE2_CERT_FILE}"
          EOF
          
          chmod 644 "${RKE2_REGISTRY_YAML}"
          echo "✓ RKE2 registries.yaml created"
          
          # Also configure containerd certs.d (for compatibility)
          echo "Also configuring containerd certs.d directory..."
          mkdir -p "${CONTAINERD_CERTS_DIR}"
          cp "${MOUNTED_CERT}" "${CONTAINERD_CERT_FILE}"
          chmod 644 "${CONTAINERD_CERT_FILE}"
          echo "✓ containerd certs.d configured"
          
          echo "✓ Certificate configuration complete"
          echo "RKE2 registries.yaml: ${RKE2_REGISTRY_YAML}"
          echo "Certificate file: ${RKE2_CERT_FILE}"
          echo ""
          echo "Note: RKE2 service may need to be restarted for changes to take effect."
          echo "The certificate is configured, but you may need to run:"
          echo "  sudo systemctl restart rke2-agent  # or rke2-server on control-plane nodes"
          echo ""
          echo "Keeping container running to maintain configuration..."
          while true; do
            # Verify certificate and config files still exist every 60 seconds
            if [ ! -f "${RKE2_CERT_FILE}" ] || [ ! -f "${RKE2_REGISTRY_YAML}" ]; then
              echo "Warning: Certificate or config missing, re-applying..."
              mkdir -p "${RKE2_REGISTRY_DIR}"
              cp "${MOUNTED_CERT}" "${RKE2_CERT_FILE}"
              chmod 644 "${RKE2_CERT_FILE}"
              cat > "${RKE2_REGISTRY_YAML}" <<EOF
          mirrors:
            "${HARBOR_URL}":
              endpoint:
                - "https://${HARBOR_URL}"
          configs:
            "${HARBOR_URL}":
              tls:
                ca_file: "${RKE2_CERT_FILE}"
          EOF
              chmod 644 "${RKE2_REGISTRY_YAML}"
            fi
            sleep 60
          done
        securityContext:
          privileged: true
        volumeMounts:
        - name: harbor-cert
          mountPath: /cert
          readOnly: true
        - name: rke2-containerd-certs
          mountPath: /var/lib/rancher/rke2/agent/etc/containerd/certs.d
        - name: rke2-registry-config
          mountPath: /etc/rancher/rke2
      volumes:
      - name: harbor-cert
        secret:
          secretName: harbor-ca-cert
          items:
          - key: ca.crt
            path: ca.crt
      - name: rke2-containerd-certs
        hostPath:
          path: /var/lib/rancher/rke2/agent/etc/containerd/certs.d
          type: DirectoryOrCreate
      - name: rke2-registry-config
        hostPath:
          path: /etc/rancher/rke2
          type: DirectoryOrCreate
      restartPolicy: Always
