# Wazuh Server Service
#
# SIEM Integration Service - Exposes Wazuh Server for:
# - Agent connections (port 1514: TCP, port 1515: UDP) - ClusterIP only
# - Syslog/SIEM reception (port 514: UDP) - LoadBalancer with external IP
# - API access (port 55000) - ClusterIP only
#
# For SIEM integrations (UniFi, etc.), use the LoadBalancer external IP on port 514 UDP
#
apiVersion: v1
kind: Service
metadata:
  name: wazuh-server
  namespace: managed-tools
  labels:
    app: wazuh
    component: server
    managed-by: gitops
  annotations:
    service.beta.kubernetes.io/load-balancer-source-ranges: "0.0.0.0/0"  # Adjust for your network
spec:
  type: LoadBalancer
  ports:
  - name: agent-tcp
    port: 1514
    targetPort: 1514
    protocol: TCP
  - name: agent-udp
    port: 1515
    targetPort: 1515
    protocol: UDP
  - name: syslog-udp
    port: 514
    targetPort: 514
    protocol: UDP
    # Standard SIEM syslog port 514 (UDP)
  - name: api
    port: 55000
    targetPort: 55000
    protocol: TCP
  selector:
    app: wazuh
    component: server
