# Wazuh Server StatefulSet
# Based on official Wazuh Kubernetes manifests
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: wazuh-server
  namespace: managed-tools
  labels:
    app: wazuh
    component: server
    managed-by: gitops
spec:
  serviceName: wazuh-server
  replicas: 1
  selector:
    matchLabels:
      app: wazuh
      component: server
  template:
    metadata:
      labels:
        app: wazuh
        component: server
        managed-by: gitops
    spec:
      volumes:
        - name: filebeat-config
          configMap:
            name: wazuh-server-filebeat-config
        - name: indexer-certs
          secret:
            secretName: wazuh-certs
            defaultMode: 0600
        - name: syslog-config
          configMap:
            name: wazuh-server-syslog-config
            defaultMode: 0755
        - name: unifi-decoder-config
          configMap:
            name: wazuh-unifi-decoder-config
            defaultMode: 0755
        - name: ossec-etc
          emptyDir: {}
          # EmptyDir volume for /var/ossec/etc (initContainer copies default files here and modifies them)
      initContainers:
        # InitContainer 1: Copy default config files and inject syslog configuration
        - name: configure-ossec
          image: wazuh/wazuh-manager:4.14.1
          command: ["/bin/bash", "-c"]
          args:
            - |
              set -e
              echo "=== Step 1: Copying default /var/ossec/etc files to emptyDir ==="
              # Ensure target directory exists
              mkdir -p /tmp/ossec-etc
              # Copy entire /var/ossec/etc directory structure (default from image)
              if [ -d "/var/ossec/etc" ]; then
                cp -a /var/ossec/etc/* /tmp/ossec-etc/ 2>/dev/null || true
                # Copy hidden files (but not . and ..)
                for file in /var/ossec/etc/.[^.]*; do
                  [ -e "$file" ] && cp -a "$file" /tmp/ossec-etc/ 2>/dev/null || true
                done
                echo "✅ Copied default /var/ossec/etc files"
              else
                echo "⚠️  /var/ossec/etc not found, using empty structure"
              fi
              
              # Ensure custom directories exist
              mkdir -p /tmp/ossec-etc/decoders/custom
              mkdir -p /tmp/ossec-etc/rules/custom
              echo "✅ Created custom decoder and rules directories"
              
              echo "=== Step 2: Injecting syslog remote configuration ==="
              # Use Python to inject syslog remote block into ossec.conf
              # Note: Wazuh allows multiple <ossec_config> blocks, but we'll insert into the first one
              python3 << 'PYTHON_SCRIPT'
              import sys
              import re
              
              ossec_conf = "/tmp/ossec-etc/ossec.conf"
              syslog_fragment = "/tmp/syslog-config/syslog-remote.xml"
              
              # Read the default ossec.conf
              with open(ossec_conf, 'r') as f:
                  content = f.read()
              
              # Check if syslog remote already exists - if so, remove it first (we'll re-add with updated config)
              if '<connection>syslog</connection>' in content:
                  print("⚠️  Syslog remote configuration already exists, updating...")
                  # Remove existing syslog remote block (from <remote> with syslog to </remote>)
                  import re
                  # Pattern matches from <remote> with syslog connection to closing </remote>
                  pattern = r'<remote>\s*<connection>syslog</connection>.*?</remote>'
                  content = re.sub(pattern, '', content, flags=re.DOTALL)
                  print("✅ Removed existing syslog remote block, will add updated version")
              
              # Read syslog fragment
              with open(syslog_fragment, 'r') as f:
                  syslog_xml = f.read().strip()
              
              # Find the LAST closing </ossec_config> tag (in case there are multiple blocks)
              # and insert before it. Preserve indentation.
              lines = content.split('\n')
              
              # Find the last </ossec_config> tag
              last_ossec_config_idx = -1
              indent = "  "
              for i in range(len(lines) - 1, -1, -1):
                  if '</ossec_config>' in lines[i]:
                      last_ossec_config_idx = i
                      # Extract indentation
                      match = re.match(r'^(\s+)</ossec_config>', lines[i])
                      if match:
                          indent = match.group(1)
                      break
              
              if last_ossec_config_idx == -1:
                  print("❌ ERROR: Could not find </ossec_config> closing tag")
                  sys.exit(1)
              
              # Indent the syslog fragment to match
              indented_syslog_lines = [indent + line if line.strip() else line 
                                       for line in syslog_xml.split('\n')]
              indented_syslog = '\n' + '\n'.join(indented_syslog_lines)
              
              # Insert before the last </ossec_config>
              lines.insert(last_ossec_config_idx, indented_syslog)
              new_content = '\n'.join(lines)
              
              # Write back
              with open(ossec_conf, 'w') as f:
                  f.write(new_content)
              
              # Basic validation - check for XML structure (Wazuh may have multiple root elements)
              # We'll validate by checking that we have matching tags
              opening_tags = content.count('<ossec_config>')
              closing_tags = content.count('</ossec_config>')
              new_opening = new_content.count('<ossec_config>')
              new_closing = new_content.count('</ossec_config>')
              
              if new_opening == new_closing and new_opening > 0:
                  print(f"✅ Successfully injected syslog remote configuration ({new_opening} ossec_config blocks)")
              else:
                  print(f"⚠️  Warning: ossec_config tag mismatch (opening: {new_opening}, closing: {new_closing})")
              
              # Verify the syslog block was added
              if '<connection>syslog</connection>' in new_content:
                  print("✅ Verified syslog remote configuration is present")
              else:
                  print("❌ ERROR: Syslog remote configuration not found after injection")
                  sys.exit(1)
              PYTHON_SCRIPT
              
              echo "=== Step 3: Copying UniFi decoders and rules ==="
              # Copy UniFi decoder file
              if [ -f "/tmp/unifi-config/unifi_decoders.xml" ]; then
                cp /tmp/unifi-config/unifi_decoders.xml /tmp/ossec-etc/decoders/custom/unifi_decoders.xml
                chmod 640 /tmp/ossec-etc/decoders/custom/unifi_decoders.xml
                chown root:wazuh /tmp/ossec-etc/decoders/custom/unifi_decoders.xml
                echo "✅ Copied unifi_decoders.xml"
              fi
              
              # Copy UniFi rules file
              if [ -f "/tmp/unifi-config/unifi_rules.xml" ]; then
                cp /tmp/unifi-config/unifi_rules.xml /tmp/ossec-etc/rules/custom/unifi_rules.xml
                chmod 640 /tmp/ossec-etc/rules/custom/unifi_rules.xml
                chown root:wazuh /tmp/ossec-etc/rules/custom/unifi_rules.xml
                echo "✅ Copied unifi_rules.xml"
              fi
              
              echo "=== Configuration complete! ==="
              echo "✅ Syslog remote configured"
              echo "✅ UniFi decoders and rules deployed"
          volumeMounts:
            - name: syslog-config
              mountPath: /tmp/syslog-config
              readOnly: true
            - name: unifi-decoder-config
              mountPath: /tmp/unifi-config
              readOnly: true
            - name: ossec-etc
              mountPath: /tmp/ossec-etc
          securityContext:
            runAsUser: 0  # Root needed to write files and set ownership
      containers:
      - name: wazuh-server
        image: wazuh/wazuh-manager:4.14.1
        resources:
          limits:
            cpu: 2000m
            memory: 4Gi
          requests:
            cpu: 1000m
            memory: 2Gi
        ports:
          - containerPort: 1514
            name: agent-tcp
            protocol: TCP
          - containerPort: 1515
            name: agent-udp
            protocol: UDP
          - containerPort: 5140
            name: syslog-udp
            protocol: UDP
          - containerPort: 55000
            name: api
            protocol: TCP
        volumeMounts:
          - name: logs
            mountPath: /var/ossec/logs
          - name: ossec-etc
            mountPath: /var/ossec/etc
          - name: filebeat-config
            mountPath: /etc/filebeat/filebeat.yml
            subPath: filebeat.yml
            readOnly: true
          - name: indexer-certs
            mountPath: /etc/filebeat/certs/root-ca.pem
            subPath: root-ca.pem
            readOnly: true
  volumeClaimTemplates:
  - metadata:
      name: logs
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: truenas-nfs
      resources:
        requests:
          storage: 10Gi
