# Wazuh Indexer StatefulSet
#
# This is a placeholder. Replace with actual Wazuh Indexer StatefulSet
# from the official wazuh-kubernetes repository.
#
# Key requirements:
# - Use StatefulSet for persistent storage
# - Mount TLS certificates from secret
# - Configure persistent volume for data storage
# - Set appropriate resource limits
# - Use storage class: truenas-nfs (configured in overlay)
#
# To get the actual manifest:
# 1. Clone https://github.com/wazuh/wazuh-kubernetes.git
# 2. Review the indexer StatefulSet/deployment files
# 3. Adapt them to use:
#    - namespace: managed-tools
#    - labels: app: wazuh, component: indexer, managed-by: gitops
#    - storage class: truenas-nfs
#    - resource limits (see README.md for recommendations)
#
# Example structure (adapt from official manifests):
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: wazuh-indexer
  namespace: managed-tools
  labels:
    app: wazuh
    component: indexer
    managed-by: gitops
spec:
  serviceName: wazuh-indexer
  replicas: 1
  selector:
    matchLabels:
      app: wazuh
      component: indexer
  template:
    metadata:
      labels:
        app: wazuh
        component: indexer
        managed-by: gitops
    spec:
      containers:
      - name: wazuh-indexer
        image: wazuh/wazuh-indexer:4.12.0
        # Using 4.12.0 due to x86-64-v2 CPU requirement in newer versions
        # Cluster nodes don't support x86-64-v2, causing "Fatal glibc error"
        # Note: May need to try even older versions (4.11.x, 4.10.x) if 4.12.0 still fails
        # Add configuration, volumes, resources, etc.
        # Refer to official Wazuh Kubernetes manifests
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      # storageClassName will be set in overlay
      resources:
        requests:
          storage: 50Gi
