# Wazuh Server StatefulSet
#
# This is a placeholder. Replace with actual Wazuh Server StatefulSet
# from the official wazuh-kubernetes repository.
#
# Key requirements:
# - Use StatefulSet for persistent storage (logs, configuration)
# - Mount TLS certificates from secret
# - Configure persistent volume for logs and configuration
# - Set appropriate resource limits
# - Use storage class: truenas-nfs (configured in overlay)
# - Connect to wazuh-indexer service
#
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: wazuh-server
  namespace: managed-tools
  labels:
    app: wazuh
    component: server
    managed-by: gitops
spec:
  serviceName: wazuh-server
  replicas: 1
  selector:
    matchLabels:
      app: wazuh
      component: server
  template:
    metadata:
      labels:
        app: wazuh
        component: server
        managed-by: gitops
    spec:
      containers:
      - name: wazuh-server
        image: wazuh/wazuh-manager:4.13.1
        # Using 4.13.1 instead of 4.14.0 due to x86-64-v2 CPU requirement in 4.14.0
        # Cluster nodes don't support x86-64-v2, causing "Fatal glibc error"
        # Add configuration, volumes, resources, etc.
        # Refer to official Wazuh Kubernetes manifests
        # Must connect to wazuh-indexer service
  volumeClaimTemplates:
  - metadata:
      name: logs
    spec:
      accessModes: [ "ReadWriteOnce" ]
      # storageClassName will be set in overlay
      resources:
        requests:
          storage: 10Gi
