# Wazuh Indexer StatefulSet
#
# This is a placeholder. Replace with actual Wazuh Indexer StatefulSet
# from the official wazuh-kubernetes repository.
#
# Key requirements:
# - Use StatefulSet for persistent storage
# - Mount TLS certificates from secret
# - Configure persistent volume for data storage
# - Set appropriate resource limits
# - Use storage class: truenas-nfs (configured in overlay)
#
# To get the actual manifest:
# 1. Clone https://github.com/wazuh/wazuh-kubernetes.git
# 2. Review the indexer StatefulSet/deployment files
# 3. Adapt them to use:
#    - namespace: managed-tools
#    - labels: app: wazuh, component: indexer, managed-by: gitops
#    - storage class: truenas-nfs
#    - resource limits (see README.md for recommendations)
#
# Example structure (adapt from official manifests):
# Wazuh Indexer StatefulSet
# Based on official Wazuh Kubernetes manifests
# https://github.com/wazuh/wazuh-kubernetes
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: wazuh-indexer
  namespace: managed-tools
  labels:
    app: wazuh
    component: indexer
    managed-by: gitops
spec:
  serviceName: wazuh-indexer
  replicas: 1
  selector:
    matchLabels:
      app: wazuh
      component: indexer
  template:
    metadata:
      labels:
        app: wazuh
        component: indexer
        managed-by: gitops
    spec:
      securityContext:
        fsGroup: 1000
      volumes:
        - name: indexer-certs
          secret:
            secretName: wazuh-certs
            defaultMode: 0600
        - name: indexer-conf
          configMap:
            name: wazuh-indexer-config
            defaultMode: 0600
      initContainers:
        - name: volume-mount-hack
          image: busybox:latest
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 100m
              memory: 256Mi
          command:
            - sh
            - '-c'
            - 'chown -R 1000:1000 /var/lib/wazuh-indexer'
          volumeMounts:
            - name: data
              mountPath: /var/lib/wazuh-indexer
        - name: increase-the-vm-max-map-count
          image: busybox:latest
          command:
            - sysctl
            - -w
            - vm.max_map_count=262144
          securityContext:
            privileged: true
      containers:
      - name: wazuh-indexer
        image: wazuh/wazuh-indexer:4.14.1
        resources:
          limits:
            cpu: 2000m
            memory: 4Gi
          requests:
            cpu: 1000m
            memory: 2Gi
          env:
            - name: OPENSEARCH_JAVA_OPTS
              value: '-Xms2g -Xmx2g -Dlog4j2.formatMsgNoLookups=true'
            - name: CLUSTER_NAME
              value: wazuh-cluster
            - name: NETWORK_HOST
              value: "0.0.0.0"
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: DISCOVERY_SERVICE
              value: wazuh-indexer
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: DISABLE_INSTALL_DEMO_CONFIG
              value: 'true'
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            capabilities:
              add: ["SYS_CHROOT"]
          volumeMounts:
            - name: data
              mountPath: /var/lib/wazuh-indexer
            - name: indexer-certs
              mountPath: /usr/share/wazuh-indexer/config/certs/node-key.pem
              subPath: node-key.pem
              readOnly: true
            - name: indexer-certs
              mountPath: /usr/share/wazuh-indexer/config/certs/node.pem
              subPath: node.pem
              readOnly: true
            - name: indexer-certs
              mountPath: /usr/share/wazuh-indexer/config/certs/root-ca.pem
              subPath: root-ca.pem
              readOnly: true
            - name: indexer-certs
              mountPath: /usr/share/wazuh-indexer/config/certs/admin.pem
              subPath: admin.pem
              readOnly: true
            - name: indexer-certs
              mountPath: /usr/share/wazuh-indexer/config/certs/admin-key.pem
              subPath: admin-key.pem
              readOnly: true
            - name: indexer-conf
              mountPath: /usr/share/wazuh-indexer/config/opensearch.yml
              subPath: opensearch.yml
              readOnly: true
            - name: indexer-conf
              mountPath: /usr/share/wazuh-indexer/config/opensearch-security/internal_users.yml
              subPath: internal_users.yml
              readOnly: true
          ports:
            - containerPort: 9200
              name: indexer-rest
            - containerPort: 9300
              name: indexer-nodes
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
        # storageClassName will be set in overlay (truenas-nfs)
      resources:
        requests:
          storage: 50Gi
