# Wazuh Indexer StatefulSet
#
# This is a placeholder. Replace with actual Wazuh Indexer StatefulSet
# from the official wazuh-kubernetes repository.
#
# Key requirements:
# - Use StatefulSet for persistent storage
# - Mount TLS certificates from secret
# - Configure persistent volume for data storage
# - Set appropriate resource limits
# - Use storage class: truenas-nfs (configured in overlay)
#
# To get the actual manifest:
# 1. Clone https://github.com/wazuh/wazuh-kubernetes.git
# 2. Review the indexer StatefulSet/deployment files
# 3. Adapt them to use:
#    - namespace: managed-tools
#    - labels: app: wazuh, component: indexer, managed-by: gitops
#    - storage class: truenas-nfs
#    - resource limits (see README.md for recommendations)
#
# Example structure (adapt from official manifests):
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: wazuh-indexer
  namespace: managed-tools
  labels:
    app: wazuh
    component: indexer
    managed-by: gitops
spec:
  serviceName: wazuh-indexer
  replicas: 1
  selector:
    matchLabels:
      app: wazuh
      component: indexer
  template:
    metadata:
      labels:
        app: wazuh
        component: indexer
        managed-by: gitops
    spec:
      initContainers:
      - name: cert-setup
        image: busybox:latest
        command: ['sh', '-c']
        args:
        - |
          mkdir -p /certs-target
          cp /certs-source/wazuh-indexer.pem /certs-target/indexer.pem
          cp /certs-source/wazuh-indexer-key.pem /certs-target/indexer-key.pem
          chmod 644 /certs-target/indexer.pem
          chmod 644 /certs-target/indexer-key.pem
          # Ensure directory is world-readable/executable for Java SecurityManager
          chmod 755 /certs-target
          chmod 644 /certs-target/*.pem
          ls -la /certs-target/
        securityContext:
          runAsUser: 0
        volumeMounts:
        - name: certs-source
          mountPath: /certs-source
          readOnly: true
        - name: certs-target
          mountPath: /certs-target
      containers:
      - name: wazuh-indexer
        image: wazuh/wazuh-indexer:4.10.3
        # Using 4.10.3 due to x86-64-v2 CPU requirement in versions 4.11.0+
        # Cluster nodes don't support x86-64-v2, causing "Fatal glibc error"
        # 4.10.3 is the last 4.10.x release and may work on older CPUs
        securityContext:
          runAsUser: 0
          runAsGroup: 0
        volumeMounts:
        - name: certs-target
          mountPath: /etc/wazuh-indexer/certs
        - name: policy-target
          mountPath: /usr/share/wazuh-indexer/opensearch-performance-analyzer
          readOnly: false
      volumes:
      - name: certs-source
        secret:
          secretName: wazuh-certs
      - name: certs-target
        emptyDir: {}
      - name: security-policy
        configMap:
          name: wazuh-indexer-security-policy
      - name: policy-target
        emptyDir: {}
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      # storageClassName will be set in overlay
      resources:
        requests:
          storage: 50Gi
