# Wazuh Server Service
#
# SIEM Integration Service - Exposes Wazuh Server for:
# - Agent connections (port 1514: TCP, port 1515: UDP) - Internal only
# - Syslog/SIEM reception (port 514: UDP) - NodePort accessible on any cluster node
# - API access (port 55000) - Internal only
#
# For SIEM integrations (UniFi, etc.):
#   - Use any cluster node IP with NodePort 30514 (UDP)
#   - Example: 192.168.14.110:30514
#   - Note: Standard port 514 requires privileged access, using NodePort 30514 instead
#
apiVersion: v1
kind: Service
metadata:
  name: wazuh-server
  namespace: managed-tools
  labels:
    app: wazuh
    component: server
    managed-by: gitops
spec:
  type: NodePort
  ports:
  - name: agent-tcp
    port: 1514
    targetPort: 1514
    protocol: TCP
  - name: agent-udp
    port: 1515
    targetPort: 1515
    protocol: UDP
  - name: syslog-udp
    port: 514
    targetPort: 514
    protocol: UDP
    nodePort: 30514
    # NodePort 30514 maps to internal port 514 UDP
    # Use any cluster node IP:30514 for SIEM integration
  - name: api
    port: 55000
    targetPort: 55000
    protocol: TCP
  selector:
    app: wazuh
    component: server
