apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: github-runner-autoscaler
  namespace: managed-cicd
spec:
  scaleTargetRef:
    name: github-runner-deployment
  minReplicas: 2
  maxReplicas: 10
  metrics:
    # Scale based on percentage of runners in use
    # This is the primary metric for autoscaling
    - type: PercentageRunnersBusy
      scaleUpThreshold: "0.75"    # Scale up when 75% of runners are busy
      scaleDownThreshold: "0.25"  # Scale down when less than 25% are busy
      scaleUpAdjustment: 2       # Add 2 runners when scaling up
      scaleDownAdjustment: 1      # Remove 1 runner when scaling down
  
  # Scale down delay to prevent rapid scaling
  scaleDownDelaySecondsAfterScaleOut: 300  # Wait 5 minutes before scaling down
